var Key =
{
	LEFT: { val: 37, name: "Left arrow" },
	RIGHT: { val: 39, name: "Right arrow" },
	UP: { val: 38, name: "Up arrow" },
	DOWN: { val: 40, name: "Down arrow" },
	MINUS: { val: 45, name: "Minus" },
	PLUS: { val: 43, name: "Plus" },
	A: { val: 65, name: "A" },
	B: { val: 66, name: "B" },
	C: { val: 67, name: "C" },
	D: { val: 68, name: "D" },
	E: { val: 69, name: "E" },
	F: { val: 70, name: "F" },
	G: { val: 71, name: "G" },
	H: { val: 72, name: "H" },
	I: { val: 73, name: "I" },
	J: { val: 74, name: "J" },
	K: { val: 75, name: "K" },
	L: { val: 76, name: "L" },
	M: { val: 77, name: "M" },
	N: { val: 78, name: "N" },
	O: { val: 79, name: "O" },
	P: { val: 80, name: "P" },
	Q: { val: 81, name: "Q" },
	R: { val: 82, name: "R" },
	S: { val: 83, name: "S" },
	T: { val: 84, name: "T" },
	U: { val: 85, name: "U" },
	V: { val: 86, name: "V" },
	W: { val: 87, name: "W" },
	X: { val: 88, name: "X" },
	Y: { val: 89, name: "Y" },
	Z: { val: 90, name: "Z" },
	Å: { val: 221, name: "Å" },
	Ä: { val: 222, name: "Ä" },
	Ö: { val: 192, name: "Ö" },
	0: { val: 48, name: "0" },
	1: { val: 49, name: "1" },
	2: { val: 50, name: "2" },
	3: { val: 51, name: "3" },
	4: { val: 52, name: "4" },
	5: { val: 53, name: "5" },
	6: { val: 54, name: "6" },
	7: { val: 55, name: "7" },
	8: { val: 56, name: "8" },
	9: { val: 57, name: "9" },
	SHIFT: { val: 16, name: "Shift" },
	COMMA: { val: 188, name: "Comma" },
	PUNCTUATION: { val: 190, name: "Punctuation" }
};

